package com.qianwang.dao.domain.user;

import java.math.BigDecimal;
import java.util.Date;

public class HeavyCUserStat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.c_user_id
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private Integer cUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.create_time
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.presenter_id
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private Integer presenterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.register_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal registerReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.c_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal cReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.p_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal pReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.dual
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal dual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d1
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d2
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d3
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d4
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d5
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d6
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d7
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d8
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d9
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d10
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d11
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d12
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d13
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d14
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d15
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d16
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d17
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d18
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d19
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d20
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d21
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d22
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d23
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d24
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d25
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d26
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d27
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d28
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d29
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_c_user_stat.d30
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    private BigDecimal d30;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.c_user_id
     *
     * @return the value of heavy_c_user_stat.c_user_id
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public Integer getcUserId() {
        return cUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.c_user_id
     *
     * @param cUserId the value for heavy_c_user_stat.c_user_id
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setcUserId(Integer cUserId) {
        this.cUserId = cUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.create_time
     *
     * @return the value of heavy_c_user_stat.create_time
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.create_time
     *
     * @param createTime the value for heavy_c_user_stat.create_time
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.presenter_id
     *
     * @return the value of heavy_c_user_stat.presenter_id
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public Integer getPresenterId() {
        return presenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.presenter_id
     *
     * @param presenterId the value for heavy_c_user_stat.presenter_id
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setPresenterId(Integer presenterId) {
        this.presenterId = presenterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.register_reward
     *
     * @return the value of heavy_c_user_stat.register_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getRegisterReward() {
        return registerReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.register_reward
     *
     * @param registerReward the value for heavy_c_user_stat.register_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setRegisterReward(BigDecimal registerReward) {
        this.registerReward = registerReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.c_reward
     *
     * @return the value of heavy_c_user_stat.c_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getcReward() {
        return cReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.c_reward
     *
     * @param cReward the value for heavy_c_user_stat.c_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setcReward(BigDecimal cReward) {
        this.cReward = cReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.p_reward
     *
     * @return the value of heavy_c_user_stat.p_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getpReward() {
        return pReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.p_reward
     *
     * @param pReward the value for heavy_c_user_stat.p_reward
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setpReward(BigDecimal pReward) {
        this.pReward = pReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.dual
     *
     * @return the value of heavy_c_user_stat.dual
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getDual() {
        return dual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.dual
     *
     * @param dual the value for heavy_c_user_stat.dual
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setDual(BigDecimal dual) {
        this.dual = dual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d1
     *
     * @return the value of heavy_c_user_stat.d1
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD1() {
        return d1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d1
     *
     * @param d1 the value for heavy_c_user_stat.d1
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD1(BigDecimal d1) {
        this.d1 = d1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d2
     *
     * @return the value of heavy_c_user_stat.d2
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD2() {
        return d2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d2
     *
     * @param d2 the value for heavy_c_user_stat.d2
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD2(BigDecimal d2) {
        this.d2 = d2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d3
     *
     * @return the value of heavy_c_user_stat.d3
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD3() {
        return d3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d3
     *
     * @param d3 the value for heavy_c_user_stat.d3
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD3(BigDecimal d3) {
        this.d3 = d3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d4
     *
     * @return the value of heavy_c_user_stat.d4
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD4() {
        return d4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d4
     *
     * @param d4 the value for heavy_c_user_stat.d4
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD4(BigDecimal d4) {
        this.d4 = d4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d5
     *
     * @return the value of heavy_c_user_stat.d5
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD5() {
        return d5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d5
     *
     * @param d5 the value for heavy_c_user_stat.d5
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD5(BigDecimal d5) {
        this.d5 = d5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d6
     *
     * @return the value of heavy_c_user_stat.d6
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD6() {
        return d6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d6
     *
     * @param d6 the value for heavy_c_user_stat.d6
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD6(BigDecimal d6) {
        this.d6 = d6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d7
     *
     * @return the value of heavy_c_user_stat.d7
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD7() {
        return d7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d7
     *
     * @param d7 the value for heavy_c_user_stat.d7
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD7(BigDecimal d7) {
        this.d7 = d7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d8
     *
     * @return the value of heavy_c_user_stat.d8
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD8() {
        return d8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d8
     *
     * @param d8 the value for heavy_c_user_stat.d8
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD8(BigDecimal d8) {
        this.d8 = d8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d9
     *
     * @return the value of heavy_c_user_stat.d9
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD9() {
        return d9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d9
     *
     * @param d9 the value for heavy_c_user_stat.d9
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD9(BigDecimal d9) {
        this.d9 = d9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d10
     *
     * @return the value of heavy_c_user_stat.d10
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD10() {
        return d10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d10
     *
     * @param d10 the value for heavy_c_user_stat.d10
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD10(BigDecimal d10) {
        this.d10 = d10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d11
     *
     * @return the value of heavy_c_user_stat.d11
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD11() {
        return d11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d11
     *
     * @param d11 the value for heavy_c_user_stat.d11
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD11(BigDecimal d11) {
        this.d11 = d11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d12
     *
     * @return the value of heavy_c_user_stat.d12
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD12() {
        return d12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d12
     *
     * @param d12 the value for heavy_c_user_stat.d12
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD12(BigDecimal d12) {
        this.d12 = d12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d13
     *
     * @return the value of heavy_c_user_stat.d13
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD13() {
        return d13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d13
     *
     * @param d13 the value for heavy_c_user_stat.d13
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD13(BigDecimal d13) {
        this.d13 = d13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d14
     *
     * @return the value of heavy_c_user_stat.d14
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD14() {
        return d14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d14
     *
     * @param d14 the value for heavy_c_user_stat.d14
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD14(BigDecimal d14) {
        this.d14 = d14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d15
     *
     * @return the value of heavy_c_user_stat.d15
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD15() {
        return d15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d15
     *
     * @param d15 the value for heavy_c_user_stat.d15
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD15(BigDecimal d15) {
        this.d15 = d15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d16
     *
     * @return the value of heavy_c_user_stat.d16
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD16() {
        return d16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d16
     *
     * @param d16 the value for heavy_c_user_stat.d16
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD16(BigDecimal d16) {
        this.d16 = d16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d17
     *
     * @return the value of heavy_c_user_stat.d17
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD17() {
        return d17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d17
     *
     * @param d17 the value for heavy_c_user_stat.d17
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD17(BigDecimal d17) {
        this.d17 = d17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d18
     *
     * @return the value of heavy_c_user_stat.d18
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD18() {
        return d18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d18
     *
     * @param d18 the value for heavy_c_user_stat.d18
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD18(BigDecimal d18) {
        this.d18 = d18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d19
     *
     * @return the value of heavy_c_user_stat.d19
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD19() {
        return d19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d19
     *
     * @param d19 the value for heavy_c_user_stat.d19
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD19(BigDecimal d19) {
        this.d19 = d19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d20
     *
     * @return the value of heavy_c_user_stat.d20
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD20() {
        return d20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d20
     *
     * @param d20 the value for heavy_c_user_stat.d20
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD20(BigDecimal d20) {
        this.d20 = d20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d21
     *
     * @return the value of heavy_c_user_stat.d21
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD21() {
        return d21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d21
     *
     * @param d21 the value for heavy_c_user_stat.d21
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD21(BigDecimal d21) {
        this.d21 = d21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d22
     *
     * @return the value of heavy_c_user_stat.d22
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD22() {
        return d22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d22
     *
     * @param d22 the value for heavy_c_user_stat.d22
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD22(BigDecimal d22) {
        this.d22 = d22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d23
     *
     * @return the value of heavy_c_user_stat.d23
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD23() {
        return d23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d23
     *
     * @param d23 the value for heavy_c_user_stat.d23
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD23(BigDecimal d23) {
        this.d23 = d23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d24
     *
     * @return the value of heavy_c_user_stat.d24
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD24() {
        return d24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d24
     *
     * @param d24 the value for heavy_c_user_stat.d24
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD24(BigDecimal d24) {
        this.d24 = d24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d25
     *
     * @return the value of heavy_c_user_stat.d25
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD25() {
        return d25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d25
     *
     * @param d25 the value for heavy_c_user_stat.d25
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD25(BigDecimal d25) {
        this.d25 = d25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d26
     *
     * @return the value of heavy_c_user_stat.d26
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD26() {
        return d26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d26
     *
     * @param d26 the value for heavy_c_user_stat.d26
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD26(BigDecimal d26) {
        this.d26 = d26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d27
     *
     * @return the value of heavy_c_user_stat.d27
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD27() {
        return d27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d27
     *
     * @param d27 the value for heavy_c_user_stat.d27
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD27(BigDecimal d27) {
        this.d27 = d27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d28
     *
     * @return the value of heavy_c_user_stat.d28
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD28() {
        return d28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d28
     *
     * @param d28 the value for heavy_c_user_stat.d28
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD28(BigDecimal d28) {
        this.d28 = d28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d29
     *
     * @return the value of heavy_c_user_stat.d29
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD29() {
        return d29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d29
     *
     * @param d29 the value for heavy_c_user_stat.d29
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD29(BigDecimal d29) {
        this.d29 = d29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_c_user_stat.d30
     *
     * @return the value of heavy_c_user_stat.d30
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public BigDecimal getD30() {
        return d30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_c_user_stat.d30
     *
     * @param d30 the value for heavy_c_user_stat.d30
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    public void setD30(BigDecimal d30) {
        this.d30 = d30;
    }
}