package com.qianwang.dao.domain.user;

import java.util.Date;

public class LightUserChannelActionStatDayKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.register_issue
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer registerIssue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.stat_date
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Date statDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.register_issue
     *
     * @return the value of light_user_channel_action_stat_day.register_issue
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getRegisterIssue() {
        return registerIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.register_issue
     *
     * @param registerIssue the value for light_user_channel_action_stat_day.register_issue
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setRegisterIssue(Integer registerIssue) {
        this.registerIssue = registerIssue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.stat_date
     *
     * @return the value of light_user_channel_action_stat_day.stat_date
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Date getStatDate() {
        return statDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.stat_date
     *
     * @param statDate the value for light_user_channel_action_stat_day.stat_date
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setStatDate(Date statDate) {
        this.statDate = statDate;
    }
}