package com.qianwang.dao.domain.user;

public class LightUserChannelActionStatDay extends LightUserChannelActionStatDayKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.spread_type
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer spreadType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.register_area
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer registerArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.register_channel
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer registerChannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.user_count
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer userCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.sign_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer signMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.recharge_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer rechargeMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.transfer_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer transferMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.get_task_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer getTaskMembers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_user_channel_action_stat_day.verified_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    private Integer verifiedMembers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.spread_type
     *
     * @return the value of light_user_channel_action_stat_day.spread_type
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getSpreadType() {
        return spreadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.spread_type
     *
     * @param spreadType the value for light_user_channel_action_stat_day.spread_type
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setSpreadType(Integer spreadType) {
        this.spreadType = spreadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.register_area
     *
     * @return the value of light_user_channel_action_stat_day.register_area
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getRegisterArea() {
        return registerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.register_area
     *
     * @param registerArea the value for light_user_channel_action_stat_day.register_area
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setRegisterArea(Integer registerArea) {
        this.registerArea = registerArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.register_channel
     *
     * @return the value of light_user_channel_action_stat_day.register_channel
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getRegisterChannel() {
        return registerChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.register_channel
     *
     * @param registerChannel the value for light_user_channel_action_stat_day.register_channel
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setRegisterChannel(Integer registerChannel) {
        this.registerChannel = registerChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.user_count
     *
     * @return the value of light_user_channel_action_stat_day.user_count
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getUserCount() {
        return userCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.user_count
     *
     * @param userCount the value for light_user_channel_action_stat_day.user_count
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setUserCount(Integer userCount) {
        this.userCount = userCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.sign_members
     *
     * @return the value of light_user_channel_action_stat_day.sign_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getSignMembers() {
        return signMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.sign_members
     *
     * @param signMembers the value for light_user_channel_action_stat_day.sign_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setSignMembers(Integer signMembers) {
        this.signMembers = signMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.recharge_members
     *
     * @return the value of light_user_channel_action_stat_day.recharge_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getRechargeMembers() {
        return rechargeMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.recharge_members
     *
     * @param rechargeMembers the value for light_user_channel_action_stat_day.recharge_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setRechargeMembers(Integer rechargeMembers) {
        this.rechargeMembers = rechargeMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.transfer_members
     *
     * @return the value of light_user_channel_action_stat_day.transfer_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getTransferMembers() {
        return transferMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.transfer_members
     *
     * @param transferMembers the value for light_user_channel_action_stat_day.transfer_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setTransferMembers(Integer transferMembers) {
        this.transferMembers = transferMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.get_task_members
     *
     * @return the value of light_user_channel_action_stat_day.get_task_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getGetTaskMembers() {
        return getTaskMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.get_task_members
     *
     * @param getTaskMembers the value for light_user_channel_action_stat_day.get_task_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setGetTaskMembers(Integer getTaskMembers) {
        this.getTaskMembers = getTaskMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_user_channel_action_stat_day.verified_members
     *
     * @return the value of light_user_channel_action_stat_day.verified_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public Integer getVerifiedMembers() {
        return verifiedMembers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_user_channel_action_stat_day.verified_members
     *
     * @param verifiedMembers the value for light_user_channel_action_stat_day.verified_members
     *
     * @mbggenerated Tue Nov 25 14:11:51 CST 2014
     */
    public void setVerifiedMembers(Integer verifiedMembers) {
        this.verifiedMembers = verifiedMembers;
    }
}