package com.qianwang.dao.domain.user;

import java.math.BigDecimal;

public class HeavyPUserStat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.p_user_id
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private Integer pUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.c_count
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private Integer cCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.register_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal registerReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.c_reward_count
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal cRewardCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.c_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal cReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.p_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal pReward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.d1
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal d1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.d3
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal d3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.d7
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal d7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.d17_verify
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal d17Verify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heavy_p_user_stat.d30
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    private BigDecimal d30;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.p_user_id
     *
     * @return the value of heavy_p_user_stat.p_user_id
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public Integer getpUserId() {
        return pUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.p_user_id
     *
     * @param pUserId the value for heavy_p_user_stat.p_user_id
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setpUserId(Integer pUserId) {
        this.pUserId = pUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.c_count
     *
     * @return the value of heavy_p_user_stat.c_count
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public Integer getcCount() {
        return cCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.c_count
     *
     * @param cCount the value for heavy_p_user_stat.c_count
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setcCount(Integer cCount) {
        this.cCount = cCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.register_reward
     *
     * @return the value of heavy_p_user_stat.register_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getRegisterReward() {
        return registerReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.register_reward
     *
     * @param registerReward the value for heavy_p_user_stat.register_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setRegisterReward(BigDecimal registerReward) {
        this.registerReward = registerReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.c_reward_count
     *
     * @return the value of heavy_p_user_stat.c_reward_count
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getcRewardCount() {
        return cRewardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.c_reward_count
     *
     * @param cRewardCount the value for heavy_p_user_stat.c_reward_count
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setcRewardCount(BigDecimal cRewardCount) {
        this.cRewardCount = cRewardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.c_reward
     *
     * @return the value of heavy_p_user_stat.c_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getcReward() {
        return cReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.c_reward
     *
     * @param cReward the value for heavy_p_user_stat.c_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setcReward(BigDecimal cReward) {
        this.cReward = cReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.p_reward
     *
     * @return the value of heavy_p_user_stat.p_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getpReward() {
        return pReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.p_reward
     *
     * @param pReward the value for heavy_p_user_stat.p_reward
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setpReward(BigDecimal pReward) {
        this.pReward = pReward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.d1
     *
     * @return the value of heavy_p_user_stat.d1
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getD1() {
        return d1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.d1
     *
     * @param d1 the value for heavy_p_user_stat.d1
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setD1(BigDecimal d1) {
        this.d1 = d1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.d3
     *
     * @return the value of heavy_p_user_stat.d3
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getD3() {
        return d3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.d3
     *
     * @param d3 the value for heavy_p_user_stat.d3
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setD3(BigDecimal d3) {
        this.d3 = d3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.d7
     *
     * @return the value of heavy_p_user_stat.d7
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getD7() {
        return d7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.d7
     *
     * @param d7 the value for heavy_p_user_stat.d7
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setD7(BigDecimal d7) {
        this.d7 = d7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.d17_verify
     *
     * @return the value of heavy_p_user_stat.d17_verify
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getD17Verify() {
        return d17Verify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.d17_verify
     *
     * @param d17Verify the value for heavy_p_user_stat.d17_verify
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setD17Verify(BigDecimal d17Verify) {
        this.d17Verify = d17Verify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heavy_p_user_stat.d30
     *
     * @return the value of heavy_p_user_stat.d30
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public BigDecimal getD30() {
        return d30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heavy_p_user_stat.d30
     *
     * @param d30 the value for heavy_p_user_stat.d30
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    public void setD30(BigDecimal d30) {
        this.d30 = d30;
    }
}