package com.qianwang.dao.domain.user;

import java.math.BigDecimal;
import java.util.Date;

public class LightFinancialStatReal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_financial_stat_real.stat_time
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    private Date statTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_financial_stat_real.recharge
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    private BigDecimal recharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_financial_stat_real.transfer
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    private BigDecimal transfer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_financial_stat_real.refund
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    private BigDecimal refund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column light_financial_stat_real.retain
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    private BigDecimal retain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_financial_stat_real.stat_time
     *
     * @return the value of light_financial_stat_real.stat_time
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public Date getStatTime() {
        return statTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_financial_stat_real.stat_time
     *
     * @param statTime the value for light_financial_stat_real.stat_time
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public void setStatTime(Date statTime) {
        this.statTime = statTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_financial_stat_real.recharge
     *
     * @return the value of light_financial_stat_real.recharge
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public BigDecimal getRecharge() {
        return recharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_financial_stat_real.recharge
     *
     * @param recharge the value for light_financial_stat_real.recharge
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public void setRecharge(BigDecimal recharge) {
        this.recharge = recharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_financial_stat_real.transfer
     *
     * @return the value of light_financial_stat_real.transfer
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public BigDecimal getTransfer() {
        return transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_financial_stat_real.transfer
     *
     * @param transfer the value for light_financial_stat_real.transfer
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public void setTransfer(BigDecimal transfer) {
        this.transfer = transfer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_financial_stat_real.refund
     *
     * @return the value of light_financial_stat_real.refund
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public BigDecimal getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_financial_stat_real.refund
     *
     * @param refund the value for light_financial_stat_real.refund
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public void setRefund(BigDecimal refund) {
        this.refund = refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column light_financial_stat_real.retain
     *
     * @return the value of light_financial_stat_real.retain
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public BigDecimal getRetain() {
        return retain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column light_financial_stat_real.retain
     *
     * @param retain the value for light_financial_stat_real.retain
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    public void setRetain(BigDecimal retain) {
        this.retain = retain;
    }
}