package com.qianwang.mapper.user;

import java.util.List;
import java.util.Map;

import com.qianwang.dao.domain.user.HeavyPUserStat;

public interface HeavyPUserStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_p_user_stat
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    int deleteByPrimaryKey(Integer pUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_p_user_stat
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    int insert(HeavyPUserStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_p_user_stat
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    int insertSelective(HeavyPUserStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_p_user_stat
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    HeavyPUserStat selectByPrimaryKey(Integer pUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_p_user_stat
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    int updateByPrimaryKeySelective(HeavyPUserStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_p_user_stat
     *
     * @mbggenerated Wed Dec 24 13:33:41 CST 2014
     */
    int updateByPrimaryKey(HeavyPUserStat record);
    List<Map<String, Object>> getPUser(Map<String, Object> params);
    int getPUserCnt(Map<String,Object> params);

	List<Map<String, Object>> getTicketBee(Map<String, Object> params);

	int getTicketBeeCnt(Map<String, Object> params);

	List<Map<String, Object>> getChangdi();

	Map<String, Object> getXiaomifengByName(Map<String, Object> params);

	int saveXiaomifeng(Map<String, Object> params);

	Map<String, Object> getXiaomifengUserByName(Map<String, Object> params);
	Map<String, Object> getUserIdByName(String name);
}