package com.qianwang.mapper.user;

import java.util.List;
import java.util.Map;

import com.qianwang.dao.domain.user.HeavyCUserStat;

public interface HeavyCUserStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_c_user_stat
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    int deleteByPrimaryKey(Integer cUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_c_user_stat
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    int insert(HeavyCUserStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_c_user_stat
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    int insertSelective(HeavyCUserStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_c_user_stat
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    HeavyCUserStat selectByPrimaryKey(Integer cUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_c_user_stat
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    int updateByPrimaryKeySelective(HeavyCUserStat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heavy_c_user_stat
     *
     * @mbggenerated Wed Dec 24 13:32:12 CST 2014
     */
    int updateByPrimaryKey(HeavyCUserStat record);
    
    List<Map<String, Object>> getCUser(Map<String, Object> params);
    List<Map<String, Object>> getCUserByPresentId(Integer presenterId);
    int getCUserCnt(Map<String, Object> params);
}