package com.qianwang.mapper.user;

import com.qianwang.dao.domain.user.LightFinancialStatReal;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface LightFinancialStatRealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_financial_stat_real
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    int deleteByPrimaryKey(Date statTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_financial_stat_real
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    int insert(LightFinancialStatReal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_financial_stat_real
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    int insertSelective(LightFinancialStatReal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_financial_stat_real
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    LightFinancialStatReal selectByPrimaryKey(Date statTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_financial_stat_real
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    int updateByPrimaryKeySelective(LightFinancialStatReal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table light_financial_stat_real
     *
     * @mbggenerated Tue Jan 06 15:15:13 CST 2015
     */
    int updateByPrimaryKey(LightFinancialStatReal record);

	List<Map<String, Object>> getMarketIndexRealInfo(Map<String,Object> params);

	List<Map<String, Object>> getMarketIndexInfo(Map<String,Object> params);

	List<Map<String, Object>> getAssetsInfo(Map<String,Object> params);

	List<Map<String, Object>> getAssetsRealInfo(Map<String,Object> params);

    List<Map<String, Object>> getTodayDepositWithdrawInfo(Map<String, Object> params);

    List<Map<String, Object>> getLastSixWeekDepositWithdrawInfo(Map<String, Object> params);

	List<Map<String, Object>> getChongTiDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getChongTiHourInfo(Map<String, Object> params);

	List<Map<String, Object>> getOverviewInfo(Map<String, Object> params);
	List<Map<String, Object>> getOverviewInfoNew(Map<String, Object> params);

	List<Map<String, Object>> getAssetsDayInfo(Map<String, Object> params);
	List<Map<String, Object>> getCbzcChongtiDayInfo(Map<String, Object> params);
	List<Map<String, Object>> getCbzcZichanDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getAssetsHourInfo(Map<String, Object> params);

	List<Map<String, Object>> getXiaofeiDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getJiangliDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getBaochouDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getWeishangDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getBaoquanOverviewInfo(Map<String, Object> params);

	List<Map<String, Object>> getBaoquan30dInfo(Map<String, Object> params);

	List<Map<String, Object>> getBaoquan30dInfoFafang(Map<String, Object> params);

	List<Map<String, Object>> getBaoquan30dInfoXiaofei(Map<String, Object> params);

	List<Map<String, Object>> getBaoquan30dInfoTuidan(Map<String, Object> params);

	List<Map<String, Object>> getTop100RechargeInfo(Map<String, Object> params);

	List<Map<String, Object>> getTop100TransferInfo(Map<String, Object> params);

	List<Map<String, Object>> getWeishangCurrDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getWeishangTotalInfo(Map<String, Object> params);

	List<Map<String, Object>> getChongTiHourInfoForFlowChart(
			Map<String, Object> params);

	List<Map<String, Object>> getWeishangTradeScopeInfo(
			Map<String, Object> params);

	List<Map<String, Object>> getWeishangTradeScopeSumInfo(
			Map<String, Object> params);

	List<Map<String, Object>> getSocialityDayInfo(Map<String, Object> params);

	List<Map<String, Object>> getWeishangTradeScopeProductTopInfo(
			Map<String, Object> params);

	List<Map<String, Object>> getWeishangTradeScopeSellerTopInfo(
			Map<String, Object> params);

	List<Map<String,Object>> getWeishangOverviewInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangTradeClassOneDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangTradeClassDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getShangjiaOverviewInfo(Map<String, Object> params);

	List<Map<String,Object>> getOneShangjiaDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangOverviewChildInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangOverviewAllSummaryInfo(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanOrderInfo(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanGoodsInfo(Map<String, Object> params);

	int getJingxuanOrderInfoCnt(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanOrderInfoAll(Map<String, Object> params);

	int getJingxuanGoodsInfoCnt(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanGoodsInfoAll(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanEntryFluxInfo(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanOverviewInfo(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanOverviewChildInfo(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanOneDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getJingxuanDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getDanpinOverviewInfo(Map<String, Object> params);

	List<Map<String,Object>> getDanpinDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getDanpinOverviewInfoForExport(Map<String, Object> params);

	int getDanpinOverviewInfoCnt(Map<String, Object> params);

	List<Map<String,Object>> getWeishangpindaoOverviewInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangpindaoOverviewChildInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangpindaoOneDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangpindaoDayInfo(Map<String, Object> params);

	int getWeishangOrderInfoCnt(Map<String, Object> params);

	List<Map<String,Object>> getWeishangOrderInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangTradeHourInfo(Map<String, Object> params);

	List<Map<String,Object>> getWeishangTradeDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getOrderTopAmountInfo(Map<String, Object> params);

	List<Map<String,Object>> getOrderTopNumInfo(Map<String, Object> params);

	List<Map<String,Object>> getBaoquan30dInfoTest(Map<String, Object> params);

	List<Map<String,Object>> getMerChongTiDayInfo(Map<String, Object> params);

	List<Map<String,Object>> getMerChongTiHourInfo(Map<String, Object> params);
}